version: 2.1
orbs:
    node: circleci/node@4.1.0
    aws-cli: circleci/aws-cli@3.1.1
    eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - aws-cli/setup
      - eb/setup
      - run: node --version

      - run:
                name: Install Front-End Dependencies
                command: npm run frontend:install
      - run:
                name: Front-End Build
                command: npm run frontend:build
      - run:
                name: Install Back-End Dependencies
                command: npm run backend:install
      - run:
                name: Back-End Build
                command: npm run backend:build